package edu.bu.mad.jiayao.bumad2016_jiayao;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.*;
import java.util.ArrayList;

@DynamoDBTable(tableName = "Listings")
public class Listing {
    private String id;
    private String owner;
    private String address;
    private double longitude;
    private double latitude;
    private int numSpots;
    private double price;
    private String availableStarting;
    private String availableUntil;
    private ArrayList<String> approved;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "owner")
    public String getOwner() {
        return owner;
    }
    public void setOwner(String owner){
        this.owner = owner;
    }

    @DynamoDBAttribute(attributeName = "address")
    public String getAddress() {
        return address;
    }
    public void setAddress(String address) {
        this.address = address;
    }

    @DynamoDBAttribute(attributeName = "longitude")
    public double getLongitude(){
        return longitude;
    }
    public void setLongitude(double longitude){
        this.longitude = longitude;
    }

    @DynamoDBAttribute(attributeName = "latitude")
    public double getLatitude() {
        return latitude;
    }
    public void setLatitude(double latitude){
        this.latitude = latitude;
    }

    @DynamoDBAttribute(attributeName = "numSpots")
    public int getNumSpots() {
        return numSpots;
    }
    public void setNumSpots(int numSpots) {
        this.numSpots = numSpots;
    }

    @DynamoDBAttribute(attributeName = "price")
    public double getPrice(){
        return price;
    }
    public void setPrice(double price){
        this.price = price;
    }

    @DynamoDBAttribute(attributeName = "availableStarting")
    public String getAvailableStarting(){
        return availableStarting;
    }
    public void setAvailableStarting(String availableStarting){
        this.availableStarting = availableStarting;
    }

    @DynamoDBAttribute(attributeName = "availableUntil")
    public String getAvailableUntil(){
        return availableUntil;
    }
    public void setAvailableUntil(String availableUntil){
        this.availableUntil = availableUntil;
    }

    @DynamoDBAttribute(attributeName = "approved")
    public ArrayList<String> getApproved() {
        return approved;
    }
    public void setApproved(ArrayList<String> approved) {
        this.approved = approved;
    }

}
